use std::collections::{BTreeMap, BTreeSet};

use tessera::prelude::{NodeId, TileFootprint};

use super::logic::focused_node_from_attention;
use super::types::BoardScene;
use crate::{
    application::board_view_settings::{AtomDisplayMode, BoardViewSettings},
    application::editor::{
        Accidental, AtomKind, AtomView, EditorAttention, NoteName, OperatorKind, SelectionState,
        compound_atoms, connection::connection_wire_kind,
    },
    domain::board::{BoardSlot, BoardSurfaceId, SurfaceLayoutKind},
    domain::document::queries::DocumentQueries,
    domain::document::{
        AtomValue, ContainerKind, DocumentNodeKind, MusaicDocument, PlacementAddress, StackIndex,
    },
};

/// A visual projection of one authored document node.
///
/// A `BoardSceneTile` should always correspond to stable application identity
/// (`node`). It is not a renderer-local mesh id and not an empty slot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoardSceneTile {
    pub node: NodeId,
    pub address: PlacementAddress,
    pub tessera_footprint: Option<TileFootprint>,
    pub visual_kind: TileVisualKind,
    pub selected: bool,
    pub focused: bool,
    pub enterable: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TileVisualKind {
    Container(ContainerKind),
    Atom,
    Output,
    Trick,
    Generic,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoardSceneAtomCompound {
    pub members: Vec<NodeId>,
    pub display: String,
    pub anchor_slot: BoardSlot,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BoardSceneConnection {
    pub from: NodeId,
    pub to: NodeId,
    pub from_slot: BoardSlot,
    pub to_slot: BoardSlot,
    pub kind: crate::domain::document::PortSlotState,
}

/// Projects the active authored surface into renderable board data.
///
/// Empty slots remain outside this projection on purpose: they are generated by
/// the renderer as addressable placement targets. Placed document nodes become
/// `BoardSceneTile`s.
pub fn project_board_scene(
    queries: &DocumentQueries<'_>,
    attention: &EditorAttention,
    selection: &SelectionState,
    view_settings: BoardViewSettings,
) -> BoardScene {
    let active_surface = attention.active_board();
    let layout = queries
        .surface_layout(active_surface)
        .unwrap_or(SurfaceLayoutKind::Board);
    let atom_display =
        atom_display_mode_for_surface(queries.document, active_surface, layout, view_settings);
    let focused_node = focused_node_from_attention(attention);
    let focus = super::logic::render_focus_from_attention(queries, attention, active_surface);

    let mut tiles = Vec::new();
    let mut atom_rows: BTreeMap<i32, Vec<(BoardSlot, AtomView)>> = BTreeMap::new();
    let mut occupied_stack_indices = Vec::new();
    let mut occupied_board_slots = BTreeMap::new();
    let mut board_addresses_by_node = BTreeMap::new();

    for tile in queries.active_surface_tiles(active_surface) {
        let node_id = &tile.id;
        let node = match queries.node(node_id) {
            Some(node) => node,
            None => continue,
        };
        let Some(placement) = tile.placement else {
            continue;
        };
        let (address, tessera_footprint) =
            root_board_placement(queries.document, active_surface, node_id, placement.address);
        let slot = match address {
            PlacementAddress::BoardSlot(slot) => {
                occupied_board_slots.insert(slot, node_id.clone());
                board_addresses_by_node.insert(node_id.clone(), slot);
                slot
            }
            PlacementAddress::StackIndex(index) => {
                occupied_stack_indices.push(index);
                BoardSlot::new(index.0 as i32, 0)
            }
        };
        let visual_kind = match &node.kind {
            DocumentNodeKind::Tile(_) => TileVisualKind::Generic,
            DocumentNodeKind::Atom(atom) => {
                atom_rows.entry(slot.y).or_default().push((
                    slot,
                    AtomView {
                        node: node.id.clone(),
                        kind: atom_value_to_atom_kind(&atom.atom),
                    },
                ));
                TileVisualKind::Atom
            }
            DocumentNodeKind::Container(container) => TileVisualKind::Container(container.kind),
            DocumentNodeKind::Output(_) => TileVisualKind::Output,
            DocumentNodeKind::TrickInstance(_) => TileVisualKind::Trick,
            DocumentNodeKind::Arrangement(_) => TileVisualKind::Generic,
        };

        tiles.push(BoardSceneTile {
            node: node_id.clone(),
            address,
            tessera_footprint,
            enterable: matches!(node.kind, DocumentNodeKind::Container(_)),
            selected: selection.contains(node_id.clone()),
            focused: focused_node.as_ref() == Some(node_id),
            visual_kind,
        });
    }

    let mut compounds = Vec::new();
    if atom_display == AtomDisplayMode::CompoundTile {
        for (_row, mut row_atoms) in atom_rows {
            row_atoms.sort_by_key(|(slot, _)| slot.x);
            let slots = row_atoms.iter().map(|(slot, _)| *slot).collect::<Vec<_>>();
            let atoms = row_atoms
                .into_iter()
                .map(|(_, atom)| atom)
                .collect::<Vec<_>>();
            let row_compounds = compound_atoms(&atoms);
            let mut member_to_slot = BTreeMap::new();
            for (slot, atom) in slots.into_iter().zip(atoms.iter()) {
                member_to_slot.insert(atom.node.clone(), slot);
            }
            for compound in row_compounds {
                let anchor_slot = compound
                    .members
                    .first()
                    .and_then(|node| member_to_slot.get(node).copied())
                    .expect("compound members should map back to slots");
                compounds.push(BoardSceneAtomCompound {
                    members: compound.members,
                    display: compound.display,
                    anchor_slot,
                });
            }
        }
    }

    occupied_stack_indices.sort_by_key(|index| index.0);
    let occupied_set = occupied_stack_indices
        .iter()
        .map(|index| index.0)
        .collect::<BTreeSet<_>>();
    let (stack_inserts, stack_locked_slots) = match layout {
        SurfaceLayoutKind::Board => (Vec::new(), Vec::new()),
        SurfaceLayoutKind::Stack => {
            let max_index = occupied_stack_indices.iter().map(|index| index.0).max();
            let insert_index = StackIndex(match max_index {
                None => 0,
                Some(max) => max + 1,
            });
            let locked = match max_index {
                None => Vec::new(),
                Some(max) => (0..=max)
                    .filter(|index| !occupied_set.contains(index))
                    .map(StackIndex)
                    .collect(),
            };
            (vec![insert_index], locked)
        }
    };
    let mut connections = Vec::new();
    if layout == SurfaceLayoutKind::Board {
        for connection in queries.connections_on_surface(active_surface) {
            let Some(from_slot) = board_addresses_by_node.get(&connection.from).copied() else {
                continue;
            };
            let Some(to_slot) = board_addresses_by_node.get(&connection.to).copied() else {
                continue;
            };
            if from_slot == to_slot {
                continue;
            }
            connections.push(BoardSceneConnection {
                from: connection.from.clone(),
                to: connection.to.clone(),
                from_slot,
                to_slot,
                kind: connection_wire_kind(queries, &connection.from, connection.spatial_side),
            });
        }
    }

    BoardScene {
        surface: active_surface,
        layout,
        tiles,
        compounds,
        stack_inserts,
        stack_locked_slots,
        connections,
        focus,
    }
}

fn atom_display_mode_for_surface(
    document: &MusaicDocument,
    surface: BoardSurfaceId,
    layout: SurfaceLayoutKind,
    view_settings: BoardViewSettings,
) -> AtomDisplayMode {
    match layout {
        SurfaceLayoutKind::Stack => view_settings.container_interior,
        SurfaceLayoutKind::Board if surface == document.root_surface => view_settings.root_board,
        SurfaceLayoutKind::Board => view_settings.container_preview_on_root,
    }
}

fn root_board_placement(
    document: &MusaicDocument,
    surface: BoardSurfaceId,
    node_id: &NodeId,
    fallback: PlacementAddress,
) -> (PlacementAddress, Option<TileFootprint>) {
    if surface != document.root_surface {
        return (fallback, None);
    }

    let Some(placement) = document
        .tessera
        .authored_program
        .root_surface
        .placements
        .get(node_id)
    else {
        return (fallback, None);
    };

    (
        PlacementAddress::BoardSlot(placement.slot),
        Some(placement.footprint),
    )
}

fn atom_value_to_atom_kind(atom: &AtomValue) -> AtomKind {
    match atom {
        AtomValue::NoteName(note) => AtomKind::NoteName(match note {
            crate::domain::document::NoteName::A => NoteName::A,
            crate::domain::document::NoteName::B => NoteName::B,
            crate::domain::document::NoteName::C => NoteName::C,
            crate::domain::document::NoteName::D => NoteName::D,
            crate::domain::document::NoteName::E => NoteName::E,
            crate::domain::document::NoteName::F => NoteName::F,
            crate::domain::document::NoteName::G => NoteName::G,
        }),
        AtomValue::Octave(value) => AtomKind::Octave(*value),
        AtomValue::Accidental(accidental) => AtomKind::Accidental(match accidental {
            crate::domain::document::Accidental::Sharp => Accidental::Sharp,
            crate::domain::document::Accidental::Flat => Accidental::Flat,
            crate::domain::document::Accidental::Natural => Accidental::Natural,
        }),
        AtomValue::Operator(operator) => AtomKind::Operator(match operator {
            crate::domain::document::OperatorValue::Power => OperatorKind::Power,
            crate::domain::document::OperatorValue::At => OperatorKind::At,
            crate::domain::document::OperatorValue::Multiply => OperatorKind::Multiply,
            crate::domain::document::OperatorValue::Divide => OperatorKind::Divide,
        }),
        AtomValue::Number(value) => AtomKind::Number(*value),
        AtomValue::Rest => AtomKind::Rest,
    }
}
