mod compile_container;
mod compile_context;
mod compile_flow_control;
mod compile_program;
mod compile_transform;
mod flow_policy_ir;
pub(crate) mod normalize;
pub(crate) mod relations;
mod resolve_spatial_program;
pub(crate) mod stream_shape;
mod validate;
mod validate_root_graph;
mod validate_surface;

pub(crate) use compile_container::{compile_container, compile_container_ir};
pub(crate) use compile_context::CompileContext;
pub(crate) use compile_flow_control::compile_flow_control_node_ir;
pub(crate) use compile_program::compile_normalized_program;
pub(crate) use compile_transform::compile_transform_node_ir;
pub(crate) use resolve_spatial_program::{infer_input_relation, resolve_spatial_program};
pub(crate) use validate::validate_and_normalize_program;
