"""Rebuild the board's shared Monoid atlas (requires Pillow).

The solid white corner texel also paints frames and flat tile surfaces, so a
complete tile still uses one mesh and material. Font license lives beside TTF.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from musical_symbols import SYMBOLS

ROOT = Path(__file__).resolve().parents[1]
font = ImageFont.truetype(str(ROOT / "assets/fonts/Monoid-Regular.ttf"), 96)
characters = "".join(chr(n) for n in range(32, 127)) + "♯♭♮×÷↔↗↑↓≡·…"
atlas = Image.new("RGBA", (2048, 1024), (255, 255, 255, 0))
draw = ImageDraw.Draw(atlas)
draw.rectangle((0, 0, 7, 7), fill="white")
rows = ["// Generated by tools/generate_tile_glyphs.py; Monoid, MIT.",
        "#[rustfmt::skip]",
        "pub(super) fn glyph(c: char) -> Option<([f32; 4], [f32; 5])> {", "    Some(match c {"]
for i, char in enumerate(characters):
    # Monoid has no musical signs or diagonal arrows. These small geometric
    # symbols are first-party strokes rather than missing-font rectangles.

    left, top, right, bottom = font.getbbox(char, anchor="ls")
    if char in SYMBOLS:
        left, top, right, bottom = 0, -76, 66, 0
    width, height = max(right-left, 1), max(bottom-top, 1)
    x, y = (i % 16)*128 + 12, (i // 16)*128 + 12
    if char in SYMBOLS:
        for line in SYMBOLS[char]:
            draw.line([(x+a,y+b) for a,b in line], fill="white", width=5, joint="curve")
    else:
        draw.text((x-left, y-top), char, font=font, fill="white", anchor="ls", stroke_width=0)
    uv = [x/2048, y/1024, (x+width)/2048, (y+height)/1024]
    metric = [left, top, width, height, (66 if char in SYMBOLS else font.getlength(char))]
    literal = "'\\u{%x}'" % ord(char)
    rows.append(f"        {literal} => ([{', '.join(f'{v:.7f}' for v in uv)}], [{', '.join(f'{v:.4f}' for v in metric)}]),")
rows += ["        _ => return None,", "    })", "}"]
atlas.save(ROOT / "assets/ui/tile-glyphs.png")
(ROOT / "src/infrastructure/ui/tile_glyphs.rs").write_text("\n".join(rows)+"\n")
